### ISSUE TITLE
Settings- and Info-Menue not scrollable

### ISSUE THREAD

**Issue by dragricola** [tbnobody/OpenDTU#1668]
### What happened?

At small displays like smartphone displays some menu items at the bottom side of the menu lists "Settings" and "Info" are not accessible because they are outside of the display area and the menu window is not scrollable.  

### To Reproduce Bug

This problem only appears on small displays like smartphones under the menu items Settings (Einstellungen) and Info. 

### Expected Behavior

It would be fine, when configuration and informations of openDTU can be also done with a smartphone.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

v24.1.18 and many versions before

### Anything else?

![Screenshot_20240119_152824_Firefox 1](https://github.com/tbnobody/OpenDTU/assets/71822907/b9dd0a96-2792-43e3-9a1e-b97ed79eb084)

This screenshot shows an example, where the menu points below DTU-Settings are not accessible.

**Comment by nkappler** [comment]
I've just investigated this a little bit, the fix is not that trivial, since there's another case where scrolling could appear:
![grafik](https://github.com/tbnobody/OpenDTU/assets/9429273/eaf3431d-58d0-40c5-bbdd-133675e15d17)

I've tried a css only solution but since the same DOM elements are used for both layouts, it's tricky...

**Comment by nkappler** [comment]
ok I've got a solution now...
That was quite an interesting challenge, I've learned a bit more about vue.js, thanks 🥳😂

**Comment by dragricola** [comment]
`ok I've got a solution now...`

Thank you! Your solution works very fine!
