### ISSUE TITLE
[Request]View of saved energy costs

### ISSUE THREAD

**Issue by Hannes0009** [tbnobody/OpenDTU#1716]
### Is your feature request related to a problem? Please describe.

Hello,

is it possible to integrate a live view of the saved energy costs? So one can set the price of 1 kw/h in the settings and at the live view the price will be showed?

### Describe the solution you'd like

Live view with the saved energy costs ;)

**Comment by tbnobody** [comment]
Thats not possible, because
1. The energy price will change over time, therefor we would have to track the energy for each moment in time time and multiply it with the price at that specific time
2. We don't know what amount of the produced energy is fed back into the grid and what you are really using. You only save money if you're using the energy instead of feding it back into the grid for free.
