### ISSUE TITLE
Current Firmware breaks MQTT channel assignment in homeassistant config [unique_id and name]

### ISSUE THREAD

**Issue by LustigePerson** [tbnobody/OpenDTU#589]
### What happened?

I installed FW `04c7d40cdea682bd5d29bf1fb914e245a3f7270`and the next day, I noticed that in Home Assistant my sensors for Strip 1, reported the values for Strip 2, and Strip two sensors where not available at all.
I found, that the configuration is broken. All the channel names and unique IDs are shifted.

`ch0_Yieldtotal` was still ok:
```
  "name": "HM600 YieldTotal",
  "uniq_id": "XXXXX_ch0_YieldTotal",
```
However, `ch1_YieldTotal` was using the same and `unique_id` and the name had the `ch0`in it:

```
  "name": "HM600 CH0 YieldTotal",
  "uniq_id": "XXXXX_ch0_YieldTotal",
```

For `ch2_YieldTotal` it looked like this:

```
  "name": "HM600 CH1 YieldTotal",
  "uniq_id": "XXXXX_ch1_YieldTotal",
```

**If** I recall correctly, the `stat_t` was correct, but as I had ro reinstall the FW ASAP I forgot to write this down.

### To Reproduce Bug

Install the mentioned FW (probably also the current one) and check the MQTT `homeassistant/#/config` topics.
The channel numbers are shifted in the `name` and ùnique_id`. I am not sure for `stat_t` I think this was ok.

### Expected Behavior

Obviously the channel numbers should not be mixed up.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

04c7d40cdea682bd5d29bf1fb914e245a3f7270

**Comment by tbnobody** [comment]
Thank you for the hint... Will fix it this evening. 
The issue is located here:
https://github.com/tbnobody/OpenDTU/blob/f5fb62855917474992d4af568ef5e9e038bfed57/src/MqttHandleHass.cpp#L120
and here:
https://github.com/tbnobody/OpenDTU/blob/f5fb62855917474992d4af568ef5e9e038bfed57/src/MqttHandleHass.cpp#L126


The term `String(channel)` has to be replaced by `chanNum` in both cases. Then it should work as expected.
