### ISSUE TITLE
[Request] Hide the Settings / Info Tab while logged out.

### ISSUE THREAD

**Issue by rauschgiftengel** [tbnobody/OpenDTU#722]
### Is your feature request related to a problem? Please describe.

No, just an enhancement

### Describe the solution you'd like

Hide the Settings / Info Tab while logged out. While logged out nobody can change any settings, but everyone can see all data like serial numbers, ip-adresses etc. 
Imho it would be better to just see the actual dashboard unless you log in.

### Describe alternatives you've considered

simple http-auth in front of it, but dint got it working properly

**Comment by tbnobody** [comment]
> but everyone can see all data like serial numbers, ip-adresses etc.

You will see the IP address.... but who cares? You already have the IP address because you accessed the web interface.
The serial number of the inverter is shown in the dashboard as well. And I have no plans to remove it here.

If you really like to deny access to the whole interface, just disable the read only access completly
