### ISSUE TITLE
OpenDTU messing up configuration during runtime

### ISSUE THREAD

**Issue by HacksBugsAndRockAndRoll** [tbnobody/OpenDTU#83]
During normal runtime on version https://github.com/tbnobody/OpenDTU/commits/0cc6ce3 the inverter configuration seems to break.

![image](https://user-images.githubusercontent.com/61069044/184896345-cdd8af30-4848-4448-86cd-d2928babfe3c.png)

curl gives this info /serial changed, but it is the correct one)
>curl http://192.168.178.96/api/inverter/list
>{"inverter":[{"id":0,"name":"SoxSolar","serial":"114181XXXXX","type":"Unknown","max_power":[0,0,0,0]}]} 

mqqt publishes like this
![image](https://user-images.githubusercontent.com/61069044/184898881-a149434c-7dfd-4eb2-ba99-59e256692de2.png)

OpenDTU no longer pulls data from the inverter in this state.

**Comment by tbnobody** [comment]
Could you please doublecheck the heap usage on the system overview if this error occours again?

**Comment by HacksBugsAndRockAndRoll** [comment]
![image](https://user-images.githubusercontent.com/61069044/184981532-fb0cfe83-f022-4f24-87f3-37568a63d34c.png)

![image](https://user-images.githubusercontent.com/61069044/184981960-be0a843e-4ba0-44cf-9e4a-5cbb6f946eb1.png)

also the dtu is currently still in this state. Is there anything else I should look into?

**Comment by tbnobody** [comment]
The Heap usage look a little bit high, but not too much. I am currently seeing something between 108 and 110kb.

You mentioned in the other issue that this only occours for one of your two ESP's. Have you tried to reflash this one again (After a complete flash erase)? 

Do you see anything special in the serial consoole before this issue happens?

**Comment by HacksBugsAndRockAndRoll** [comment]
I opened the ticket because I thought it was the ESP hardware but now the second ESP also shows this behavior. 
Both ESPs were flash erased ~3 days ago. 
The USB is only connected to power for this ESP at the moment since I cannot get the inverters signal at my PC.
I monitored the heap usage by polling ~30s see here (captured some spikes but always seems to recover fine)
![image](https://user-images.githubusercontent.com/61069044/184990799-62a93687-470a-4a6b-a6a4-2641c69d4b5a.png)

**Comment by tbnobody** [comment]
Today, before I flashed a new version, the uptime was > 2 days without any issues. So you maybe have some kind of different config. Are you using MQTT with TLS?

**Comment by HacksBugsAndRockAndRoll** [comment]
no, just plain mqtt with HA discovery

**Comment by HacksBugsAndRockAndRoll** [comment]
it seems to be appearing only with mqtt enabled so i dug a bit in  that code and found https://github.com/tbnobody/OpenDTU/pull/86 might be related

**Comment by HacksBugsAndRockAndRoll** [comment]
finally the issue also appeared on a dtu without mqtt enabled, this was after 3d17h uptime. The dtus with mqtt enabled still seem to fail faster.

**Comment by helgeerbe** [comment]
Found this in "WebApi_ws_live.cpp" `WebApiWsLiveClass::loop()`

````cpp
DynamicJsonDocument root(40960);
        JsonVariant var = root;
        generateJsonResponse(var);

        size_t len = measureJson(root);
        AsyncWebSocketMessageBuffer* buffer = _ws.makeBuffer(len); //  creates a buffer (len + 1) for you.
        if (buffer) {
            serializeJson(root, (char*)buffer->get(), len + 1);
            _ws.textAll(buffer);
        }
````

It seems to me, that the buffer is created of the size of the Json document. But in `serializeJson()` `buffer size + 1`is used. 
Looks not correct for me. The comment indicates that in earlier code `len + 1`was allocated.

**Comment by helgeerbe** [comment]
OK, ignore my comment. I had to learn, that `makeBuffer()` indeed creates a buffer + 1 length.

**Comment by stefan123t** [comment]
@HacksBugsAndRockAndRoll are you running two ESPs in parallel and do you at least use distinct DTU_RADIO_IDs for them ?

**Comment by HacksBugsAndRockAndRoll** [comment]
Yes to both of these questions.

**Comment by tbnobody** [comment]
There should be no misinterpretation of the data when using two different DTU id's because one DTU wouldn't see the packages of the other one. Unless.... How different are the DTU id's? The RF packet only contains the lowest 4 bytes of the ID. If this  bytes are identical there might be an issue. (But the chance is very small because there are 3 different CRC checksums which have to match)

**Comment by petrm** [comment]
I observe the same issue. Restarting the ESP makes it go away. It appears randomly after 1-3 days of uptime. When it happens, the DTU is accessible via the web interface, but stops polling the inverters.

**Comment by tbnobody** [comment]
@petrm which inverter(s) are you using? Are you using mqtt? If yes, what configuration? Are you using a DTU-Lite or Pro in parallel?

**Comment by tbnobody** [comment]
@petrm and @HacksBugsAndRockAndRoll do you have a chance to log the output of the serial console for a longer time? it would be interessting what happens just before this issue. (If there is something special in the serial console)
I also added some additional debug output of the startup sequence in the meantime. This output would be also interessting.

I still try to reproduce this issue. Are you doing anything special? (e.g. poll the web api using curl etc? Or something else which I may not have in mind currently?) I am rebooting my ESP regulary because of development work but I also reach uptimes of 5-10 days without problems.

**Comment by petrm** [comment]
Since there is no way to get any log remotely, I can only attach the serial console when I am back in about three weeks.
I have a new state of the device: this time it can read the info from the inverter, it shows it in the UI, but sends it out corrupted to MQTT. When I go to the configuration page, the serial number there is displayed correctly, but inverter can't be identified. This would suggest that the serial number displayed there is read from a different place in the memory than the one actually used to query the inverter.
What would help:
1) add option to reboot remotely as a workaround
2) maybe add some debugging output also to the UI

**Comment by tbnobody** [comment]
> I have a new state of the device: this time it can read the info from the inverter, it shows it in the UI, but sends it out corrupted to MQTT. When I go to the configuration page, the serial number there is displayed correctly, but inverter can't be identified. This would suggest that the serial number displayed there is read from a different place in the memory than the one actually used to query the inverter.

This is absolutly correct. There is a config structure which stores the serial number etc. but when showing the type or exporting mqtt stuff the internal data structures of the hoymiles library are used. There is an vector which stores the inverters inside the hoymiles lib:
https://github.com/tbnobody/OpenDTU/blob/9a443248ed61ab55a5544bd3f2847e1297a4a6bf/lib/Hoymiles/src/Hoymiles.h#L30

Anywhere in the code a part of this structure gets partly overwritten. (And therefor any future functionality is totally random). But this does not happen for all users. I would suspect some issue with the packet parser but without knowing the exact received packets its a little bit hard to analyze. (And due to the memory corruption it might be also wrong in an web output)

**Comment by HacksBugsAndRockAndRoll** [comment]
Since I do not have a computer in a location where the DTU is in range to the inverter I'll need to set something up probably with a raspberry - this might take some time. 
On a sidenote: the corruptions also happen during the night time when the inverter was offline. See attached graph where I track the uptime of the devices using 30s interval polls to the rest api. 

To further explain this, I have my fork running on these two DTUs the only change I made is a regular detection for corrupted DTU serials in the configuration - in case a corruption is found a restart is triggered ( https://github.com/HacksBugsAndRockAndRoll/OpenDTU/blob/local/configfix-workaroud/src/ConfigFix.cpp - I know this is not the solution to the problem, but it is what allows me to use openDTU for my "productive" setup as long as the bug exists ). 

The blue line shows the device with MQTT enabled which seems to increase the chance of corruption - also this device shows the corruptions during the night time. 

![image](https://user-images.githubusercontent.com/61069044/191821321-bfce5fe1-b23f-4e69-b8f6-76c659fc4b70.png)

**Comment by tbnobody** [comment]
If the corruption also occours during the night time it's maybe not related to the response of the inverter. But then it should be sufficient if you place one of your ESP's out of range of the inverter but connected to a computer to get the serial output.

**Comment by tbnobody** [comment]
Can you maybe download your config file (Settings --> Config Management), open the .bin file using a hex editor, overwrite your WiFi password with X (do not change the length of the file, just overwrite the characters) and provide this in some way? Then I can import your config with all applied settings and see if this issue occurs.

**Comment by petrm** [comment]
Here is my config
[config.zip](https://github.com/tbnobody/OpenDTU/files/9664554/config.zip)
I upgraded to the last checkin and no crash for 6 days.

**Comment by petrm** [comment]
Short update. I now have 20 days uptime with [d7fe495](https://github.com/tbnobody/OpenDTU/commits/d7fe495) and so far stable, no suspicious log messages or errors.

**Comment by stefan123t** [comment]
@tbnobody havent looked into OpenDTU for the `Serial.flush()` buffer. But in AhoyDTU I also have some suspicions that we may need to flush the Serial buffers from time to time in order not to reach a buffer overflow.
@HacksBugsAndRockAndRoll did you try the version that @petrm has tested for 20 days being rock-solid ?

**Comment by HacksBugsAndRockAndRoll** [comment]
Currently I do not have a whole lot of time for this project. I can say, that I am running https://github.com/tbnobody/OpenDTU/commits/59b87c5 which is a slightly adjusted (self reset on corrupted config) version of https://github.com/tbnobody/OpenDTU/commit/9a443248ed61ab55a5544bd3f2847e1297a4a6bf and I still see the self resets triggered.

![image](https://user-images.githubusercontent.com/61069044/202031125-50e71a1b-21e2-4ec1-9829-64208b8454ef.png)

I'll need to rebase my stuff and update some time.

**Comment by stefan123t** [comment]
@HacksBugsAndRockAndRoll as we are unable to reproduce this issue on other devices,
could you report that with a newer build OpenDTU v23.12.19 or something newer ?

**Comment by tbnobody** [comment]
Would close this issue as it's really old and there where a lot of code iterations. Please open a new one if the problem occours again.
